LLAVA_CLIP_PATH = 'openai/clip-vit-large-patch14-336'
LLAVA_MODEL_PATH = 'liuhaotian/llava-v1.5-13b'
SDXL_PATH = 'SG161222/RealVisXL_V4.0'
FAITHDIFF_PATH =  'jychen9811/FaithDiff'
VAE_FP16_PATH = 'madebyollin/sdxl-vae-fp16-fix'
BSRNet_PATH = './checkpoints/BSRNet.pth'